name: Build and Deploy React App to S3

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: react-build
        path: build  # Upload the build directory

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy step only runs if build succeeds

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: react-build

    - name: Sync S3 Bucket
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'react-build'  # The downloaded build directory